### Why Pytorch? 

1. Eager execution (Graph is constructed in a dynamic way)
2. Tensor library with GPU acceleration
3. Simplicity
4. Ease of moving from research to production (python to C++)

#### Some tensor operations and their properties

In [1]:
import torch

In [4]:
# Everything in torch is a tensor, with an implicit data type, device location
rand_x = torch.rand(5, 3)
print(rand_x)
zeros = torch.zeros_like(rand_x)
print(zeros)
print(rand_x.shape)
print(rand_x.size())

tensor([[ 0.3404,  0.8985,  0.3675],
        [ 0.5315,  0.8720,  0.0051],
        [ 0.1406,  0.3545,  0.1580],
        [ 0.2726,  0.4869,  0.1328],
        [ 0.9369,  0.7303,  0.3762]])
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])
torch.Size([5, 3])
torch.Size([5, 3])


In [7]:
# tensor operations
y = torch.ones_like(rand_x, dtype=torch.float)
print(rand_x + y)
print(torch.add(rand_x, y))
print("Before addition x was", rand_x)
rand_x.add_(y) # inplace addition !!! changes values of rand_x
print(rand_x)

tensor([[ 1.3404,  1.8985,  1.3675],
        [ 1.5315,  1.8720,  1.0051],
        [ 1.1406,  1.3545,  1.1580],
        [ 1.2726,  1.4869,  1.1328],
        [ 1.9369,  1.7303,  1.3762]])
tensor([[ 1.3404,  1.8985,  1.3675],
        [ 1.5315,  1.8720,  1.0051],
        [ 1.1406,  1.3545,  1.1580],
        [ 1.2726,  1.4869,  1.1328],
        [ 1.9369,  1.7303,  1.3762]])
Before addition x was tensor([[ 0.3404,  0.8985,  0.3675],
        [ 0.5315,  0.8720,  0.0051],
        [ 0.1406,  0.3545,  0.1580],
        [ 0.2726,  0.4869,  0.1328],
        [ 0.9369,  0.7303,  0.3762]])
tensor([[ 1.3404,  1.8985,  1.3675],
        [ 1.5315,  1.8720,  1.0051],
        [ 1.1406,  1.3545,  1.1580],
        [ 1.2726,  1.4869,  1.1328],
        [ 1.9369,  1.7303,  1.3762]])


In [9]:
# indexing
print(rand_x[:, 1], rand_x[2, :], rand_x[:3, :2]) # numpy like indexing :)
# resizing
view_x = rand_x.view(1, -1) # tensor.view(a, b) will return a new tensor, recommended method
reshaped_x = rand_x.reshape(1, -1) # tensor.reshape(a, b) will return a new tensor
print(rand_x.size())
resized_x = rand_x.resize_(1, -1) # since tensor.resize_(a, b) is inplace operations, it changes the values of x, upredictable
print(rand_x.size()) 

tensor([ 1.8985,  1.8720,  1.3545,  1.4869,  1.7303]) tensor([ 1.1406,  1.3545,  1.1580]) tensor([[ 1.3404,  1.8985],
        [ 1.5315,  1.8720],
        [ 1.1406,  1.3545]])
torch.Size([5, 3])
torch.Size([1])


In [15]:
print(view_x.size())
print(reshaped_x.size())
print(resized_x) #

torch.Size([1, 15])
torch.Size([1, 15])
tensor([ 1.3404])


In [21]:
# numpy bridge
y = torch.ones(5, 5, dtype=torch.float)
print(type(y))
np_y = y.numpy() # tensor.numpy()  returns the numpy equivalent of same tensor sharing a common memory location
print(np_y, type(np_y))

y.add_(5) # changing y also impacts np_y since they share a common memory location
print(y)
print(np_y)

# numpy to tensor
tensor_y = torch.from_numpy(np_y)
print(type(tensor_y))

<class 'torch.Tensor'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>
tensor([[ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.]])
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
<class 'torch.Tensor'>


In [24]:
# moving tensors to CUDA and CPU
print(torch.cuda.is_available()) # checks whether there is a cuda device available
if torch.cuda.is_available():
    device = torch.device("cuda") # cuda object
    x = torch.randn(5, 5, device=device) # creating a new tensor on this device
    y = y.to(device) # moving y to cuda
    z = x + y # adding taking on cuda device
    print(z)
    print(z.to("cpu")) # moving the tensor to cpu

True
tensor([[ 5.8328,  6.9538,  6.6606,  4.9969,  7.1488],
        [ 6.8675,  5.7050,  4.9898,  7.1841,  4.6847],
        [ 5.8786,  7.7159,  5.8238,  6.9145,  6.1509],
        [ 8.0610,  5.4459,  5.6590,  5.4418,  6.6304],
        [ 6.8168,  7.6326,  6.9963,  7.1424,  6.4644]], device='cuda:0')
tensor([[ 5.8328,  6.9538,  6.6606,  4.9969,  7.1488],
        [ 6.8675,  5.7050,  4.9898,  7.1841,  4.6847],
        [ 5.8786,  7.7159,  5.8238,  6.9145,  6.1509],
        [ 8.0610,  5.4459,  5.6590,  5.4418,  6.6304],
        [ 6.8168,  7.6326,  6.9963,  7.1424,  6.4644]])
